### ISSUE TITLE
К openssl не подключается GOST 

### ISSUE THREAD

**Issue by peektoseen** [RekGRpth/gost.docker#1]
Приветствую. Пришёл в надежде, что работает. Оказалось что нет :(

```
 docker run -ti ghcr.io/rekgrpth/gost.docker:debian openssl ciphers | tr ":" "\n" | grep GOST
 ```
 
 Должен вывести поддерживаемые шифры ГОСТ, но не выводит -- openssl без поддержки GOST

**Comment by RekGRpth** [comment]
да, вы правы, на старом openssl 1.1.1 ghcr.io/rekgrpth/gost.docker:alpine_3_16 есть, а на новом - нету, буду разбираться...

**Comment by RekGRpth** [comment]
хотя
```sh
docker run -it --rm ghcr.io/rekgrpth/gost.docker:debian openssl engine -t gost
(gost) Reference implementation of GOST engine
     [ available ]
```

**Comment by peektoseen** [comment]
Нашёл решение. 
Нужно добавить сертификат в доверенные:
```
openssl s_client -connect esia.gosuslugi.ru:443 -showcerts </dev/null | awk '/-----BEGIN CERTIFICATE-----/, /-----END CERTIFICATE-----/' >  /usr/local/share/ca-certificates/esia-cert.crt
update-ca-certificates
```

Не уверен, что это безопасный путь. Лучше забирать сертификаты из достоверного источника. Если домен скомпрометирован - то получится что скомпрометированный сертификат попадёт в доверенные.

**Comment by RekGRpth** [comment]
а вот так работает?

```sh
openssl s_client -engine gost -connect esia.gosuslugi.ru:443 -showcerts
```

**Comment by peektoseen** [comment]
> Нашёл решение. Нужно добавить сертификат в доверенные:
> 
> ```
> openssl s_client -connect esia.gosuslugi.ru:443 -showcerts </dev/null | awk '/-----BEGIN CERTIFICATE-----/, /-----END CERTIFICATE-----/' >  /usr/local/share/ca-certificates/esia-cert.crt
> update-ca-certificates
> ```
> 
> Не уверен, что это безопасный путь. Лучше забирать сертификаты из достоверного источника. Если домен скомпрометирован - то получится что скомпрометированный сертификат попадёт в доверенные.

Да, прошу прощения, это не то решение. Просто все решения которые находил делятся на два случая:
1) не подключен gost engine в openssl и работает curl на https://esia.gosuslugi.ru (наш случай)
2) engine подключен, но curl перестает отрабатывать (случай, для которого выше написал решение

**Comment by RekGRpth** [comment]
а какова исходная задача? я в своё время делал авторизацию через есиа, но там гост нужен был не для https, а для подписания запроса

**Comment by peektoseen** [comment]
Да, авторизация и нужна была. Но её уже сделал. 
Для авторизации использую https://github.com/ekapusta/oauth2-esia  , они в свою очередь наследуются от https://github.com/thephpleague/oauth2-client 
А там внутри делается запрос на госуслуги для получения токена. В частности -- вот здесь : https://github.com/thephpleague/oauth2-client/blob/24552000ce6014e1c3991ae56d7c4ef04e649ee9/src/Provider/AbstractProvider.php#L635C31-L635C56

**Comment by peektoseen** [comment]
> ```shell
> openssl s_client -engine gost -connect esia.gosuslugi.ru:443 -showcerts
> ```

нет, так тоже висит долго и возвращает:
```
40A7DFE4FD7E0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:303:
```

**Comment by peektoseen** [comment]
Нашёл в чём проблема. 
В /etc/ssl/openssl.cnf была пустая секция openssl_init
А должно быть:
```
[openssl_init]
engines = engine_section
```

Сделал PR https://github.com/RekGRpth/gost.docker/pull/2

**Comment by RekGRpth** [comment]
спасибо!
